name: time_plus
description: "Extensions for DateTime and Duration to easily add, convert, and work with time in Dart."
version: 0.0.6
homepage: https://github.com/jozzzzep/time_plus
repository: https://github.com/jozzzzep/time_plus
issue_tracker: https://github.com/jozzzzep/time_plus/issues
topics:
  - date
  - time
  - duration
  - datetime
  - date_time

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:

dev_dependencies:
  test: ^1.26.1
  lints: ^5.1.1
